---
title: "Comparing the classification of GPS points by different axes"
output:
  html_document:
    toc: true
    toc_depth: 4
    theme: cerulean
    highlight: zenburn
    self_contained: true
---


# Set workspace

```{r global_options, include=FALSE}

# Global options
# fig_path = "Rmd_output"
# if( !dir.exists(fig_path)) dir.create(fig.path)

knitr::opts_chunk$set(
                      # fig.width=12, fig.height=8,
                      # fig.path=fig_path,
                      echo=TRUE, warning=FALSE, message=FALSE)

options(DT.options = list(pageLength = 25,
                          dom = 'Btip',
                          filter = "top",
                          extensions = 'Buttons',
                          buttons = c('copy', 'csv')))


```


```{r}

# ==============================================================================
# * Environment
# ==============================================================================
source("R/00_fxns.R")

library(cowplot)
library(dplyr)
library(data.table)
library(tidyr)
library(knitr)
library(kableExtra)
library(ggplot2)
library(finalfit)

```

# Import acceleration and GPS data

```{r, results = 'hide'}

acc_behavL_files = list.files("data/acc_behavL", full.names = TRUE)
acc_behavL_all = lapply(acc_behavL_files, readRDS)

```

# Compare acc results across axes

```{r}

axes = lapply(acc_behavL_files, function(fn) strsplit(basename(fn), "_")[[1]][1]) %>%
    unlist()

acc_all = lapply(acc_behavL_all, function(acc_behavL) {
    acc_behav = lapply(acc_behavL, `[[`, "acc_behav")
})

gps_all = lapply(acc_behavL_all, function(acc_behavL) {
    gps_behav = lapply(acc_behavL, `[[`, "gps_behav")
})

get_activity_info = function(type_all, axes) {
    type_activityL = lapply(type_all, function(type_behav) {
        type_activity = lapply(type_behav, function(df)
            as.data.frame(table(df$activity)))
        mapply(cbind, type_activity,
               "tagID" = names(type_activity), SIMPLIFY = FALSE) %>%
            rbindlist() %>%
            spread(Var1, Freq) %>%
            as.data.frame()
    })
    type_activity = mapply(cbind, type_activityL, "axis" = axes, SIMPLIFY = FALSE) %>%
        rbindlist()
    split(type_activity, type_activity$tagID)
}

acc_info = get_activity_info(acc_all, axes)
gps_info = get_activity_info(gps_all, axes)


```

```{r, results = 'asis'}

names(gps_all) = axes
tagIDs = names(gps_all[[ 1 ]])

gps_all = lapply(axes, function(axis, gps_all) {
    mapply(cbind, gps_all[[ axis ]], "axis" = axis, SIMPLIFY = FALSE)
}, gps_all)

gps_unlist = unlist(gps_all, recursive = FALSE)

gps_by_bats = lapply(tagIDs, function(ID, gps_unlist) {
    ID_n = grep(ID, names(gps_unlist))
    gps_unlist[ ID_n ] %>% rbindlist
}, gps_unlist)

for(df in gps_by_bats) {

    ID = unique(df$tagID)

    color_group = c("#8C0C53", "#F2CB70")

    gps_leg = data.frame(activity = rep(c("Flying", "Not Flying"), 2),
                         n = 1:4, x = 1:4) %>%
        ggplot(aes(x = x, y = n)) +
        geom_point(aes(color = activity)) +
        scale_color_manual(values = color_group, name = "Classification") +
        theme(legend.position = "top",
              legend.justification='center',
              legend.key.size = unit(0.2, "cm"))

    gps_leg = get_legend(gps_leg)

    g = ggplot() +
        geom_path(data = df, aes(x = location.long, y = location.lat),
                  size = 0.25, color = "#8C0C53") +
        geom_point(data = df, aes(x = location.long, y = location.lat),
                   color = "#8C0C53",
                   size = 1, alpha = 1) +
        geom_point(data = df[ df$activity %in% "NotFlying", ],
                   aes(x = location.long, y = location.lat), color = "#F2CB70",
                   size = 1, alpha = 1) +
        theme_classic() +
        scale_x_continuous(
            labels = label_fill) +
        ggtitle(ID) +
        xlab("Longitude") +
        ylab("Latitude") +
        facet_wrap(. ~ axis, nrow = 1)


    g = plot_grid( gps_leg, g, ncol = 1, rel_heights = c(.03, 1))

    
    cat("\n\n")
    cat("-----------------------------------------------------------------------")
    cat("\n")
    
    cat("### GPS classification for ", ID, "using different axes\n")
        
    print(kable(table(df$axis, df$activity)) %>%
          kable_styling(full_width = FALSE, position = "left"))
    
    cat('\n')
    
    print(g)

}



```

# Testing for differences between xyz, xz, and yz axes classification
```{r}

gps_df = lapply(gps_all, rbindlist) %>%rbindlist

gps_df = gps_df %>%
    filter(axis %in% c("xyz", "xz", "yz")) %>%
    mutate(Flying = ifelse(activity %in% "Flying", 1, 0)) %>%
    mutate_at(vars(Flying, axis, tagID), as.factor)


explanatory = c("axis", "tagID")
dependent = "Flying"

table1 = gps_df %>%
    as.data.frame() %>%
  summary_factorlist(dependent, explanatory, 
  p=TRUE, na_include=TRUE, 
  add_dependent_label=TRUE)

table2 = gps_df %>% 
  finalfit(dependent, explanatory, 
           dependent_label_prefix = "")

```

<br>

### Table 1 - Axes groups (XYZ, XZ, YZ), bats, and Flying/NotFlying
```{r table1, echo = FALSE, results='asis'}
kable(table1, row.names=FALSE, align=c("l", "l", "r", "r", "r", "r")) %>%
     kable_styling(full_width = TRUE)
```

<br>

### Table 2 - Association between axes groups and Flying/NotFlying
```{r table2, echo = FALSE, results='asis'}
kable(table2, row.names=FALSE, align=c("l", "l", "r", "r", "r", "r")) %>%
      kable_styling(full_width = TRUE)

```

<br>

### Figure 1 - Association between axes groups and Flying/NotFlying
```{r figure1, echo = FALSE, warning=FALSE, message=FALSE, fig.width=10}
gps_df %>% 
  or_plot(dependent, explanatory, breaks = c(0.5, 1, 2))
```

# Session info

```{r}
sessionInfo()
```
