---
title: "Home ranges for e-obs tagged bats"
output:
  html_document:
    toc: true
    toc_depth: 4
    theme: cerulean
    highlight: zenburn
    self_contained: true
---

# Setting up the workspace
	
```{r global_options, include=FALSE}
 
 # Global options
 knitr::opts_chunk$set(fig.width=12, fig.height=8,
                       # fig.path=fig.path,
                       echo=TRUE, warning=FALSE, message=FALSE)

 options(DT.options = list(pageLength = 25,
                           dom = 'Btip',
                           filter = "top",
                           extensions = 'Buttons',
                           buttons = c('copy', 'csv')))


```

```{r set-up}


# ==============================================================================
# * Libraries
# ==============================================================================

library(move)
library(adehabitatHR)
library(dplyr)
library(data.table)
library(sf)
library(ggplot2)
library(ggsn)
library(hrbrthemes)
library(patchwork)

source("R/00_fxns.R")

# Directory for saving plots and KDE information
plot_out_dir = file.path("results", "maps", "kde")
kde_info_out_dir = file.path("results", "tables")

invisible(lapply(c(plot_out_dir, kde_info_out_dir), function(out_dir)
    if( !dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)))

```

<br><br>

# Kernel Density Estimation

```{r kde}

# ==============================================================================
# * Read in the behavior-classified gps data
# ==============================================================================
acc_gps_behavL = readRDS("data/acc_behavL/yz_acc_gps_behavL.RDS")

kilombero_lonlat = data.frame(site = "kilombero",
                           lon = 277974.9,
                           lat = 9152539)

kilombero = st_as_sf(kilombero_lonlat, coords = c("lon", "lat"), crs = 32737)
    

gpsALL = lapply(acc_gps_behavL, `[[`, "gps_behav") %>%
    rbindlist() %>%
    as.data.frame()


# Subset "not flying" gps fixes
# ------------------------------------------------------------------------------

gpsALl = gpsALL[ gpsALL$activity %in% "NotFlying", ]

    
# ==============================================================================
# * Home range Estimation (using KDE method)
# ==============================================================================
bats_df = gpsALL[, c("tagID", "utm.easting", "utm.northing")]
bats_sf = st_as_sf(bats_df, coords = c("utm.easting", "utm.northing"), crs = 32737)
bats_sp = as(bats_sf, 'Spatial')

bats_ud <- kernelUD(bats_sp, h = "href")  # href = the reference bandwidth

if(FALSE) {
    mcp95 <- mcp(bats_sp[ ,"tagID"], percent = 95)
    mcp50 <- mcp(bats_sp[ ,"tagID"], percent = 50)
}


ud50 = getverticeshr(bats_ud, percent = 50)
ud95 = getverticeshr(bats_ud, percent = 95)

# Make data frames for ggplot
ud50_df = fortify(ud50)
ud95_df = fortify(ud95)

# Split to make individual plots
ud50L = split(ud50_df, ud50_df$id)
ud95L = split(ud95_df, ud95_df$id)

# KDE areas (in ha)
ud50_area = ud50 %>%
    as.data.frame() %>%
    mutate(area = round(area, 2)) %>%
    rename(KDE_50_ha = area)

ud95_area = ud95 %>%
    as.data.frame() %>%
    mutate(area = round(area, 2)) %>%
    rename(KDE_95_ha = area)
    

ud_area = dplyr::left_join(ud50_area, ud95_area, by = "id")

DT::datatable(ud_area, options = list(dom = 't'))

```


<br><br>

# Plot 50% and 95% KDE countours

```{r plot-kde}

# ** Plot KDE
# ==============================================================================
tagIDs = unique(bats_sp$tagID)

color_palette = c("#E58606", "#5D69B1", "#52BCA3", "#99C945",
                   "#CC61B0", "#24796C", "#DAA51B", "#2F8AC4",
                   "#764E9F", "#ED645A", "#CC3A8E", "#A5AA99")

tag_colors = color_palette[ 1:length(tagIDs) ]
names(tag_colors) = tagIDs

small_area_IDs = c("K5313", "K5315", "K5319")
large_area_IDs = "K5310"
medium_area_IDs = tagIDs[ ! tagIDs %in% c(small_area_IDs, large_area_IDs) ]

small_extent = extent(bats_sp[ bats_sp$tagID %in% small_area_IDs, ]) %>%
    as('SpatialPolygons') %>%
    st_as_sf %>%
    st_set_crs(st_crs(bats_sp)) %>%
    st_buffer(1500)


medium_extent = extent(bats_sp[ bats_sp$tagID %in% medium_area_IDs, ]) %>%
    as('SpatialPolygons') %>%
    st_as_sf %>%
    st_set_crs(st_crs(bats_sp)) %>%
    st_buffer(1000)

large_extent = extent(bats_sp[ bats_sp$tagID %in% large_area_IDs, ]) %>%
    as('SpatialPolygons') %>%
    st_as_sf %>%
    st_set_crs(st_crs(bats_sp)) %>%
    st_buffer(100)


plot_kde = function(ID, bats_df, ud50L, ud95L, tag_colors, map_extent, kilombero) {
    ind_bat = bats_df[ bats_df$tagID %in% ID, ]
    ind_ud50 = ud50L[[ ID ]]
    ind_ud95 = ud95L[[ ID ]]
    col = tag_colors[ ID ]
    g = ggplot() +
        geom_sf(data = map_extent, fill = NA, color = NA) +
        geom_polygon(data = ind_ud50, aes(x = long, y = lat),
                     alpha = 0.6, fill = col) +
        geom_polygon(data = ind_ud95, aes(x = long, y = lat),
                     alpha = 0.4, fill = col) +
        geom_path(data = ind_bat, aes(x = utm.easting, y = utm.northing),
                   color = "black", size = .05) +
        geom_point(data = ind_bat, aes(x = utm.easting, y = utm.northing),
                   color = "black", size = 0.1, alpha = 0.3) +
        geom_sf(data = kilombero, color = "white", size = 2, aes(shape = site)) +
        scale_shape_manual(values = 8) +
        ggthemes::scale_fill_gdocs() +
        theme_ipsum(base_size = 12,
                    plot_title_size = 14,
                    axis_title_size = 12,
                    axis_text_size = 10,
                    grid = FALSE,
                    axis = FALSE, ticks = TRUE) +
        theme(legend.position="none") +
        coord_sf() +
        scalebar(map_extent, dist = 4, dist_unit = "km",
                 location = "topleft",
                 height = 0.01,
                 st.dist = 0.05,
                 st.size = 3,
                 box.fill = c("grey", "black"),
                 box.color = NA,
                 transform = FALSE) +
        scale_x_continuous(
            labels=label_fill) +
        scale_y_continuous(
            labels=label_fill) +
        xlab("Longitude") +
        ylab("Latitude") +
        ggtitle(ID) 
    g
}


p_sm = lapply(small_area_IDs, plot_kde,
           bats_df, ud50L, ud95L, tag_colors, map_extent = small_extent, kilombero)

names(p_sm) = small_area_IDs
p_sm_all = (p_sm$K5313 | p_sm$K5315 | p_sm$K5319)


p_med = lapply(medium_area_IDs, plot_kde,
           bats_df, ud50L, ud95L, tag_colors, map_extent = medium_extent, kilombero)

names(p_med) = medium_area_IDs
p_med_all = (p_med$K5309 | p_med$K5311) / (p_med$K5312 | p_med$K5317)


p_large = plot_kde(large_area_IDs, bats_df, ud50L, ud95L,
                   tag_colors, map_extent = large_extent, kilombero)

```

## Bats with relatively smaller 95% KDE areas (96.88 to 1437.45 ha)
```{r, echo = FALSE}
p_sm_all
```


## Bats with relatively medium 95% KDE areas (4861.94 to 18985.86 ha)
```{r, echo = FALSE}
p_med_all
```

## Bat with relatively larger 95% KDE area (124413.78 ha)
```{r, echo = FALSE}
p_large
```


<br><br>

# Save KDE area information and KDE plots

```{r save-results}

write.csv(ud_area, file.path(kde_info_out_dir, "KDE-area_eobs.csv"))

cowplot::save_plot(file.path(plot_out_dir, "KDE_small_area.png"),
                   p_sm_all, base_width = 12, base_height = 8, dpi = 600)
cowplot::save_plot(file.path(plot_out_dir, "KDE_med_area.png"),
                   p_med_all, base_width = 12, base_height = 8, dpi = 600)
cowplot::save_plot(file.path(plot_out_dir, "KDE_large_area.png"),
                           p_large, base_width = 12, base_height = 8, dpi = 600)

```

<br><br>

# Session info
```{r session-info}

sessionInfo()

```
