---
title: "GPS data processing for table output"
output:
  html_document:
    toc: true
    toc_depth: 4
    theme: cerulean
    highlight: zenburn
    self_contained: true
---

# Setting up the workspace
	
```{r global_options, include=FALSE}
 
 # Global options
 knitr::opts_chunk$set(fig.width=12, fig.height=8,
                       # fig.path=fig.path,
                       echo=TRUE, warning=FALSE, message=FALSE)

 options(DT.options = list(pageLength = 25,
                           dom = 'Btip',
                           filter = "top",
                           extensions = 'Buttons',
                           buttons = c('copy', 'csv')))


```


```{r set-up}

# ==============================================================================
# * Libraries
# ==============================================================================

library(move)
library(lubridate)
library(dplyr)
library(data.table)
library(leaflet)
library(htmlwidgets)
library(sf)
library(ggplot2)
library(patchwork)
library(ggsn)
library(hrbrthemes)
library(DT)
library(viridis)
library(tidyr)
library(readxl)
library(cowplot)
source("R/00_fxns.R")

# Directory for saving plots and KDE information
plot_out_dir = file.path("results", "figs")
gps_info_out_dir = file.path("results", "tables")


# ==============================================================================
# * Read in GPS data with flying behaviour + tagging location
# ==============================================================================
# read in the behavior-classified acc and GPS data
gps = readRDS("data/gps_forage.RDS")
hr = read.csv("results/tables/KDE-area_eobs.csv", stringsAsFactors = FALSE)
hr$X = NULL

bats = read.csv("data/raw/bats/eobs_info.csv", stringsAsFactors = FALSE)
bats = bats[ , c("tagID", "location", "tag_type", "sex", "body_wt", "date")]
bats$tagID = paste0("K", bats$tagID)

```

<br><br>

# GPS information

```{r}

# * GPS time range
# ==============================================================================
gps_info = bats

tr = lapply(gps, function(df)
    data.frame(ts_min = min(df$timestamp),
               ts_max = max(df$timestamp))) %>%
    rbindlist()

gps_info = gps_info %>%
    mutate(
        date_deployed = format(tr$ts_min, "%b-%d"),
        hours = round(time_length(tr$ts_max - tr$ts_min, "hours"), 2),
        days = round(time_length(tr$ts_max - tr$ts_min, "days"), 2))

gps_info$foraging_nights = sapply(gps, function(df)
    max(df$time_cut, na.rm = TRUE))

gps_info$gps_fixes = sapply(gps, nrow)


# ==============================================================================
# * Cumulative distances
# ==============================================================================
dist_info = sapply(gps, function(bat) {
    nightly_dist = sapply(split(bat, bat$time_cut), get_dist_km)
    dist_mean = round(mean(nightly_dist), 2)
    dist_range = paste0(round(range(nightly_dist), 2), collapse = ", ")
    cum_dist = paste0(dist_mean, " (", dist_range, ")")
})

gps_info$cum_dist_km = dist_info

nightly_dist = lapply(gps, function(bat) {
    dists = sapply(split(bat, bat$time_cut), get_dist_km)
    data.frame(night = seq_along(dists), dists = dists, total_nights = length(dists))
})


dist_df = mapply(cbind, nightly_dist, "tagID" = names(nightly_dist),
                 SIMPLIFY = FALSE) %>%
    rbindlist()


night_dist = dist_df %>%
    mutate(dists = round(dists, 2)) %>%
    spread(night, dists) %>%
    arrange(tagID)


color_palette = c("#7F3C8D", "#3969AC", "#E68310",
                  "#E73F74", "#008695", "#CF1C90",
                  "#f97b72", "#4b4b8f")


dist_p = dist_df %>%
    mutate(tagID = paste0(tagID, " (", total_nights, " nights)")) %>%
    ggplot( aes(x = night, y = dists, color = tagID)) +
    geom_line(size = 0.5) +
    geom_point(size = 1) +
    ggtitle("Nightly cumulative distance flown by bats") +
    xlab("Foraging night") +
    ylab("Distance (km)") +
    scale_color_manual(values = color_palette) +
    theme_ipsum(base_size = 12, axis_title_size = 12, axis_text_size = 10) +
    theme(panel.grid.minor.x = element_blank()) +
    scale_x_continuous(limits = c(0, 7), breaks = 0:7) +
    labs(color = "Bat (nights tracked)")

night_dist
dist_p

write.csv(night_dist, file.path(gps_info_out_dir, "eobs_night-dist-info.csv"))
cowplot::save_plot(file.path(plot_out_dir, "line_nightly_dist.png"),
                   dist_p, base_height = 6)
                             

# ==============================================================================
# Add home range information
# ==============================================================================
gps_info = left_join(gps_info, hr, by = c("tagID" = "id"))
# gps_info


# ==============================================================================
# Add forage info
# ==============================================================================
gps_forage_n = gps %>%
    rbindlist() %>%
    dplyr::select(tagID, forage_pts) %>%
    filter(forage_pts) %>%
    group_by(tagID) %>%
    summarize(forage_n = n()) %>%
    as.data.frame()

gps_info = left_join(gps_info, gps_forage_n, by = "tagID")

kilombero_lonlat = data.frame(site = "kilombero",
                           lon = 277974.9,
                           lat = 9152539)

kilombero = st_as_sf(kilombero_lonlat, coords = c("lon", "lat"), crs = 32737)


forage_dist = lapply(gps, function(df, kilombero) {
    df_sf = df %>%
        st_as_sf(coords = c("utm.easting", "utm.northing"), crs = 32737)
    # first_loc = df_sf[1, ]
    forage_loc = df_sf[ df$forage_pts, ]
    dists = st_distance(kilombero, forage_loc)/1000
    dists = as.numeric(dists)
    summary(dists)
    data.frame(tagID = df$tagID[1],
               max_straightline_forage_dist_km = round(max(dists), 2),
               stringsAsFactors = FALSE)
}, kilombero) %>% rbindlist()

gps_info = left_join(gps_info, forage_dist, by = "tagID")


# ==============================================================================
# Add max dist between day roosts
# ==============================================================================

roost_dist = lapply(gps, function(df) {
    df_sf = df %>%
        st_as_sf(coords = c("utm.easting", "utm.northing"), crs = 32737)
    roost_loc = df_sf[ df$DayTime %in% "day" , ]
    dist_df = data.frame(tagID = df$tagID[1],
                         max_straightline_roost_dis_km = NA,
                         stringsAsFactors = FALSE)
    if(nrow(roost_loc) > 1){
        dists = st_distance(roost_loc, roost_loc)/1000
        dists = as.numeric(dists)
        dist_df$max_straightline_roost_dis_km = round(max(dists), 2)
    }
    dist_df
}) %>% rbindlist()

gps_info = left_join(gps_info, roost_dist, by = "tagID")
        
    
gps_info

write.csv(gps_info, file.path(gps_info_out_dir, "eobs_gps-info.csv"))

```


<br><br>

# Hourly distance travelled and heat maps

```{r}
# ==============================================================================
# * Remove GPS points taken just at 7 am
# ==============================================================================
# These points would corespond to when the logger was getting a fix just
# before 7 am and the corresponding timestamp is milliseconds into 7 am
gps %>% rbindlist %>%
    mutate(gps_hour = hour(timestamp)) %>%
    filter(gps_hour %in% 7) %>%
    select(tagID, timestamp)
               
gps = lapply(gps, function(df) {
    gps_hour = hour(df$timestamp)
    df[ !gps_hour %in% 7, ]
})

# ==============================================================================
# Calculate hourly distances
# ==============================================================================
hourly_dist_info = lapply(gps, function(bat, lat, lon) {
    bat$night_hour = paste0(bat$time_cut, "_", hour(bat$timestamp))
    night_hour_dist = round(sapply(split(bat, bat$night_hour), get_dist_km, lon, lat), 2)
    hours = sapply(strsplit(names(night_hour_dist), "_"), `[[`, 2)
    hourly_dist = data.frame(hour = as.numeric(hours),
                             dist = as.numeric(night_hour_dist))
    hourly_dist %>%
        group_by(hour) %>%
        summarize(mean_dist = mean(dist),
                  min_dist = min(dist),
                  max_dist = max(dist)) %>%
        mutate_at(vars(mean_dist, min_dist, max_dist), round, 2) %>%
        as.data.frame()
}, lon = "utm.easting", lat = "utm.northing")

hourly_dist_info = Map(cbind, hourly_dist_info, tagID = names(gps)) %>%
    rbindlist

hour_df = data.frame(hour = c(17:23, 0:6))
hour_df$hour_order = factor(hour_df$hour, levels = rev(hour_df$hour))
hour_df = left_join(hour_df, hourly_dist_info, by = "hour")

hour_dist_hm = ggplot(data = hour_df,
                      mapping = aes(x = tagID, y = hour_order, fill = mean_dist)) +
    geom_tile() +
    xlab("Bat ID") +
    ylab("Hour") +
    labs(fill = "Mean distance \ntravelled (km)") +
    theme_ipsum(base_size = 14,
                plot_title_size = 14,
                axis_title_size = 14,
                grid = FALSE,
                axis = FALSE, ticks = TRUE) +
    scale_fill_viridis(direction = -1)


hour_tbl = hour_df %>%
    mutate(dist_info = paste0(mean_dist, " (", min_dist, ", ", max_dist, ")")) %>%
    dplyr::select(hour_order, tagID, dist_info) %>%
    spread(key = tagID, value = dist_info) %>%
    arrange(desc(hour_order))

hour_tbl

hour_dist_hm


# ==============================================================================
# Hourly distances travelled by bats by nights
# ==============================================================================
night_hourly_dist_info = lapply(gps, function(bat, lat, lon) {
    bat$night_hour = paste0(bat$time_cut, "_", hour(bat$timestamp))
    night_hour_dist = round(sapply(split(bat, bat$night_hour), get_dist_km, lon, lat), 2)
    nights = sapply(strsplit(names(night_hour_dist), "_"), `[[`, 1)
    hours = sapply(strsplit(names(night_hour_dist), "_"), `[[`, 2)
    hourly_dist = data.frame(night = nights,
                             hour = as.numeric(hours),
                             dist = as.numeric(night_hour_dist))
}, lon = "utm.easting", lat = "utm.northing")

night_hourly_dist_info = Map(cbind, night_hourly_dist_info, tagID = names(gps)) %>%
    rbindlist

night_hour_df = data.frame(hour = c(17:23, 0:6))
night_hour_df$hour_order = factor(night_hour_df$hour, levels = rev(night_hour_df$hour))
night_hour_df = left_join(night_hour_df, night_hourly_dist_info, by = "hour")


night_hour_p = ggplot(data = night_hour_df,
                      aes(x = night, y = hour_order, fill = dist)) +
    geom_tile() +
    xlab("Foraging night") +
    ylab("Hour") +
    ggtitle(paste0("Hourly distance travelled by bats for each tracked night")) +
    labs(fill = "Distance \ntravelled (km)") +
    theme_ipsum(base_size = 12,
                plot_title_size = 14,
                axis_title_size = 12,
                grid = FALSE,
                axis = FALSE, ticks = TRUE) +
    scale_fill_viridis(direction = -1) +
    facet_wrap( . ~ tagID, ncol = 4, scales = "free")


hour_summary = night_hour_df %>%
    group_by(tagID) %>%
    summarize(mean = mean(dist),
              min = min(dist),
              max = max(dist))

hour_summary

night_hour_p


# ==============================================================================
# Save heatmaps and nightly dist information
# ==============================================================================
write.csv(hour_tbl, file.path(gps_info_out_dir, "eobs_hour-dist-info.csv"))
write.csv(hour_summary, file.path(gps_info_out_dir, "eobs_hour-dist-summary.csv"))
          
hm_fn = file.path(plot_out_dir, "heatmap_hour-dist.png")
cowplot::save_plot(hm_fn, hour_dist_hm, base_height = 10, dpi = 600)

hm_night_fn = file.path(plot_out_dir, "heatmap_hour-dist-night.png")
cowplot::save_plot(hm_night_fn, night_hour_p, base_height = 10, dpi = 600)

```





