theme: jekyll-theme-minimal
title: [Code for paper]
description: [Randhawa, N., Bird, B.H., VanWormer, E. et al. Fruit bats in flight: a look into the movements of the ecologically important Eidolon helvum in Tanzania. One Health Outlook 2, 16 (2020). https://doi.org/10.1186/s42522-020-00020-9]
